### ISSUE TITLE
Expose per-route counters for throughput and frame types

### ISSUE THREAD

**Issue by jfallows** [reaktivity/reaktor.java#24]
For each route, track the total input and output throughput in bytes and the total number of each input and output frame type across all associated high-level application streams.

The reaktor should internally keep these counts up-to-date without requiring specific per-nukleus participation.

Requires reaktivity/reaktor.java#23.

**Comment by dpwspoon** [comment]
Design was to add to counters file the frames and bytes per Connect/Connect Reply routes.  PRs are here: 

https://github.com/reaktivity/nukleus.java/pull/9
https://github.com/reaktivity/reaktor.java/pull/29
https://github.com/reaktivity/nukleus-sse.java/pull/8 <-- other nuklei can be done after this design/pr is merged, as they will all be very similar

**Comment by dpwspoon** [comment]
All these are merged
