### ISSUE TITLE
Observe when a nukleus reaktor is ready to accept commands (i.e. Control files are created)

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/reaktor.java#38]
I'm starting a long running nukleus reaktor, and then a control reaktor.  The control reaktor sets the initial configuration via commands to control files in the nukleus reaktor.  There is a race between the nukleus reaktor creating the control files and control reaktor writing the initial commands to them.

It would be nice to have an API to know when the control files have been created.  (Work around for now is to add a sleep).

**Comment by jfallows** [comment]
There is no longer a race, unified `control` file is now created synchronously when `reaktor` is created.
